- name: Check webserver running 
  hosts: localhost
  tasks:
  - name: check web page content
    uri:
      url: http://centos-frontend-01
      status_code: 200

# Check that a page returns a status 200 and fail if the word AWESOME is not
# in the page contents.
  - name: check if the word AWESOME is not
    uri:
      url: http://centos-frontend-01
      return_content: yes
    register: webpage

  - name: Fail if AWESOME is not in the page content
    fail:
    when: "'AWESOME' not in webpage.content"
