- name: setu_custom fact
  hosts: web
  become: yes
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
  - name: create remote directory
    file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}" 
  - name: copy file
    copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
