- name: install apache thru custome facts
  hosts: web
  become: yes
  tasks:
  - name: install httpd 
    yum: 
      name: "{{ ansible_local.custom.general.package }}"
      state: latest
  - name: start httpd service
    service:
      name: "{{ ansible_local.custom.general.service }}"
      state: "{{ ansible_local.custom.general.state }}"
      enabled: "{{ ansible_local.custom.general.enabled }}"
