---
- hosts: db
  become: yes
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
      ignore_errors: yes  

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest
