- name: create secure web service
  hosts: secure_webserver
  vars:
    random_var: This is colon: test

  tasks:
    - block:
        - name: install web server packages
          yum:
            name: {{ item }}
            state: latest
          notify:
            - restart services
          tags:
            - packages
          loop:
            - httpd
            - mod_ssl
            - crypto-utils

        - name: install httpd config files
          template:
            src: vhosts.conf
            dest: /etc/httpd/conf.d/vhosts.conf
            backup: yes
            owner: root
            group: root
            mode: 0644
            force: yes
          register: vhosts_config
          notify:
            - restart services
          tags:
            - config

        - name: create ssl certificate
          command: openssl req -new -nodes -x509 -subj "/C=US/ST=North Carolina/L=Raleigh/O=Example Inc/CN=app1.{{GUID}}.internal" -days 120 -keyout /etc/pki/tls/private/app1.{{GUID}}.internal.key -out /etc/pki/tls/certs/app1.{{GUID}}.internal.crt -extensions v3_ca
          args:
            creates: /etc/pki/tls/certs/app1.{{GUID}}.internal.crt

         - name: start and enable web services
           service:
             name: httpd
             state: started
             enabled: yes
           tags:
             - services

        - name: deliver content
          copy:
            dest: /var/www/vhosts/app1-secure
            src: html/

        - name: check httpd syntax
          command: /sbin/httpd -t
          register: httpd_conf_syntax
          failed_when: "'Syntax OK' not in httpd_conf_syntax.stderr"

        - name: httpd_conf_syntax variable
          debug: msg="The httpd_conf_syntax variable value is {{ httpd_conf_syntax }}"

        - name: check httpd status
          command: /sbin/service httpd status
          register: httpd_status_output
          failed_when: "'Active: failed' in httpd_status_output.stdout"
          changed_when: "'Active: inactive' in httpd_status_output.stdout"
          notify:
            - restart services

      rescue:
        - name: recover original httpd config
          file:
            path: /etc/httpd/conf.d/vhosts.conf
            state: absent
          notify:

        - name: email notification of httpd config status
          mail:
            to: student@app1.{{GUID}}.internal
            subject: 'httpd config is not correct'
            body: "httpd syntax is {{httpd_conf_syntax.stdout}}"
          when: httpd_conf_syntax.stdout != 'Syntax OK'
           - restart services

  handlers:
    - name: restart services
      service:
        name: httpd
        state: restarted
